#!/usr/bin/env node
/**
 * ui/build.js — Bundle DolbyX Web UI into a single HTML file + C header
 *
 * Pipeline:
 *   1. esbuild bundles + minifies CSS and JS
 *   2. Script inlines both into index.html
 *   3. Outputs ui/dist/bundle.html
 *   4. Generates ui/dist/ui_bundle.h via xxd-style C array
 *
 * Usage: node build.js
 */

const { buildSync } = require('esbuild');
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');
const DIST = path.join(__dirname, 'dist');

// Ensure dist exists
fs.mkdirSync(DIST, { recursive: true });

// Bundle CSS
const cssResult = buildSync({
  entryPoints: [path.join(SRC, 'style.css')],
  bundle: true,
  minify: true,
  write: false,
});
const css = cssResult.outputFiles[0].text;

// Bundle JS
const jsResult = buildSync({
  entryPoints: [path.join(SRC, 'app.js')],
  bundle: true,
  minify: true,
  write: false,
  target: 'es2020',
});
const js = jsResult.outputFiles[0].text;

// Read HTML template
let html = fs.readFileSync(path.join(SRC, 'index.html'), 'utf8');

// Inline CSS: replace <link rel="stylesheet" ...> with <style>
html = html.replace(
  /<link\s+rel="stylesheet"\s+href="[^"]*"\s*\/?>/,
  `<style>${css}</style>`
);

// Inline JS: replace <script src="..."></script> with inline <script>
html = html.replace(
  /<script\s+src="[^"]*"><\/script>/,
  `<script>${js}</script>`
);

// Write bundle.html
const bundlePath = path.join(DIST, 'bundle.html');
fs.writeFileSync(bundlePath, html);
console.log(`  bundle.html: ${html.length} bytes`);

// Generate C header (xxd -i style)
const bytes = Buffer.from(html, 'utf8');
let cHeader = `/* Auto-generated by ui/build.js — do not edit */\n`;
cHeader += `static const unsigned char ui_bundle_html[] = {\n`;

const COLS = 16;
for (let i = 0; i < bytes.length; i++) {
  if (i % COLS === 0) cHeader += '  ';
  cHeader += `0x${bytes[i].toString(16).padStart(2, '0')}`;
  if (i < bytes.length - 1) cHeader += ',';
  if (i % COLS === COLS - 1 || i === bytes.length - 1) cHeader += '\n';
}

cHeader += `};\n`;
cHeader += `static const unsigned int ui_bundle_html_len = ${bytes.length};\n`;

const headerPath = path.join(DIST, 'ui_bundle.h');
fs.writeFileSync(headerPath, cHeader);
console.log(`  ui_bundle.h: ${cHeader.length} bytes (${bytes.length} byte payload)`);
